### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by phoenix6936** [CodeWithTamim/Convertit#7]
request :
Hello, if possible, add a part so that when the pr is committed, it will show that the software has no problem to Build apk
![IMG_۲۰۲۴۱۲۱۲_۲۰۴۴۱۶](https://github.com/user-attachments/assets/2dd94480-ce0e-4dbf-90c4-40449422814f)

**Comment by CodeWithTamim** [comment]
Hello, yes but currently we are not accepting any pr , cause it's being migrated to jetpack compose.
